### PR TITLE
Added a heading for screen readers to clarify the purpose of a link in the page navigation.

### PR DESCRIPTION
**Pull request by milk54**
Language files only modify Japanese and English. So please add another language.

Heading is not visible and is hidden in a way screen readers will still read it aloud. See 

https://webaim.org/techniques/css/invisiblecontent/

for the reasons behind the way the text is hidden. Added css class "gl-screen-reader-only" which can be used to hide other text which will be read by screen readers.

### CODE REVIEW

**Comment by milk54** [comment]
I fix to conform with Success Criterion 2.4.4.

**Comment by milk54** [comment]
I fixed to conform with Success Criterion 2.4.4.
[Link Purpose (In Context): Understanding SC 2.4.4](https://www.w3.org/TR/2016/NOTE-UNDERSTANDING-WCAG20-20161007/navigation-mechanisms-refs.html)

**Comment by milk54** [comment]
I could not think of an appropriate the set_var for the page navigation .
I change the variable name from lang_sr to lang_page_navigation.

People who gained information visually will soon understand page navigation.
But Screen reader users are hard to understand what links are.
So, I added the page navigation heading for screen reader users.
I wrote to read it with a screen reader, but hidden text on screen.

**Comment by eSilverStrike** [comment]
Ahhh I was wondering what the "sr" was referring too and why the text was hidden.

https://webaim.org/techniques/css/invisiblecontent/

2 more small updates then  if you could

1) Since the css class can be used for other potential screen reading text, lets change the name of the css class to something like "gl-screen-reader-only" were "gl" refers to a Geeklog specific class.
2) Add a small comment beside the Page Navigation heading
 
<h3 class="gl-screen-reader-only">{lang_page_navigation}</h3> {# Visible to screen readers only #}

and then I will merge it.

**Comment by milk54** [comment]
Thank you for advice.  I fixed it.

**Pull request merged**
